### ISSUE TITLE
Support Sublime Text 3

### ISSUE THREAD

**Issue by patik** [keeganstreet/sublime-elfinder#4]
Please package the plugin for Sublime Text 3 so it can be maintained with Package Control. Thanks.

**Comment by keeganstreet** [comment]
I have created an Element Finder package for [Atom](https://atom.io/). Sorry I don't have any plans to release a Sublime Text 3 package but if somebody else who knows Python wants to, please go ahead.

**Comment by thinkv** [comment]
Might be a bit late, but https://github.com/keeganstreet/sublime-elfinder/pull/6

**Comment by keeganstreet** [comment]
Thank-you very much to @thinkv who has released Element Finder for ST3. This plugin will now be maintained at https://github.com/thinkv/sublime-elfinder.
